# Generated by Django 2.2.5 on 2021-02-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_link',
            field=models.TextField(blank=True),
        ),
    ]
