# Generated by Django 2.2.5 on 2021-02-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group_code',
            field=models.ForeignKey(blank=True, db_column='group_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Group'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_status',
            field=models.BooleanField(default=False),
        ),
    ]
